language: node_js

env:
  - CXX=g++-4.8

node_js:
  - "6"
  - "5"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - npm cache clean -f
  - npm install -g gulp
  - npm install -g mocha
  - npm install

script:
  - gulp

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

sudo: false
