language: node_js
node_js:
  - "6"
  - "5"

before_script:
  - sudo apt-get update
  - sudo apt-get install imagemagick graphicsmagick
  - npm install -g gulp
  - npm install -g mocha
  - npm install

script:
  - gulp

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

sudo: true
